/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["AppController_getHello"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/countries": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List all countries
		 * @description Retrieve a list of countries with optional filters (name, ISO codes)
		 */
		get: operations["CountryController_getAll"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/countries/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get country by ID
		 * @description Retrieve detailed information about a specific country
		 */
		get: operations["CountryController_getById"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/departments": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List all departments
		 * @description Retrieve a list of departments with optional filters (name, DANE code, country)
		 */
		get: operations["DepartmentController_findAll"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/departments/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get department by ID
		 * @description Retrieve detailed information about a specific department
		 */
		get: operations["DepartmentController_findOne"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/cities": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List all cities
		 * @description Retrieve a list of cities with optional filters (country, department, name, DANE code)
		 */
		get: operations["CityController_getAll"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/cities/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get city by ID
		 * @description Retrieve detailed information about a specific city
		 */
		get: operations["CityController_getById"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/neighborhoods/point": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get neighborhood by geographic coordinates
		 * @description Find the neighborhood at a specific geographic point (latitude, longitude)
		 */
		get: operations["NeighborhoodController_getByPoint"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		CountryDto: {
			/**
			 * @description Identificador único del país
			 * @example 48
			 */
			id: number;
			/**
			 * @description Nombre del país en español
			 * @example Colombia
			 */
			name_es: string;
			/**
			 * @description Nombre del país en inglés
			 * @example Colombia
			 */
			name_en: string;
			/**
			 * @description Código ISO alpha-2 (2 letras)
			 * @example CO
			 */
			iso_alpha2_code?: string;
			/**
			 * @description Código ISO alpha-3 (3 letras)
			 * @example COL
			 */
			iso_alpha3_code?: string;
			/**
			 * @description Código numérico ISO
			 * @example 170
			 */
			iso_numeric_code?: number;
		};
		DepartmentDto: {
			/**
			 * @description Identificador único del departamento
			 * @example 5
			 */
			id: number;
			/**
			 * @description Nombre del departamento
			 * @example Atlántico.
			 */
			name: string;
			/**
			 * @description Código DANE del departamento
			 * @example 08
			 */
			dane_code?: string;
			/**
			 * @description ID del país al que pertenece
			 * @example 48
			 */
			country_id?: number;
		};
		CityWithRelationsDto: {
			/**
			 * @description Identificador único de la ciudad
			 * @example 91
			 */
			id: number;
			/**
			 * @description Nombre de la ciudad
			 * @example Bogotá
			 */
			name: string;
			/**
			 * @description Código DANE de la ciudad
			 * @example 001
			 */
			dane_code?: string;
			/**
			 * @description Nombre del departamento
			 * @example Atlántico
			 */
			department_name?: string;
			/**
			 * @description Código DANE del departamento
			 * @example 08
			 */
			department_dane_code?: string;
			/**
			 * @description Nombre del país
			 * @example Colombia
			 */
			country_name_es?: string;
			/**
			 * @description Nombre del país en inglés
			 * @example Colombia
			 */
			country_name_en?: string;
		};
		CityDto: {
			/**
			 * @description Identificador único de la ciudad
			 * @example 1
			 */
			id: number;
			/**
			 * @description Nombre de la ciudad
			 * @example Bogotá
			 */
			name: string;
			/**
			 * @description Código DANE de la ciudad
			 * @example 003
			 */
			dane_code?: string;
			/**
			 * @description ID del departamento al que pertenece
			 * @example 1
			 */
			department_id?: number;
			/**
			 * @description ID del país al que pertenece
			 * @example 1
			 */
			country_id?: number;
		};
		NeighborhoodDto: {
			/**
			 * @description Identificador único del barrio
			 * @example 163
			 */
			neighborhood_id: number;
			/**
			 * @description Nombre del barrio
			 * @example CORREGIMIENTO LA PLAYA
			 */
			neighborhood_name: string;
			/**
			 * @description Identificador de la ciudad
			 * @example 91
			 */
			city_id: number;
			/**
			 * @description Nombre de la ciudad
			 * @example BARRANQUILLA
			 */
			city_name: string;
			/**
			 * @description Código DANE de la ciudad
			 * @example 001
			 */
			city_dane_code: string;
			/**
			 * @description ID del departamento
			 * @example 5
			 */
			department_id: number;
			/**
			 * @description Nombre del departamento
			 * @example Atlántico
			 */
			department_name: string;
			/**
			 * @description Código DANE del departamento
			 * @example 08
			 */
			department_dane_code: string;
			/**
			 * @description ID del país
			 * @example 48
			 */
			country_id: number;
			/**
			 * @description Nombre del país
			 * @example Colombia
			 */
			country_name: string;
			/**
			 * @description Nombre de la localidad
			 * @example Otro o no especificado
			 */
			locality_name: string;
			/**
			 * @description Nombre del área urbana
			 * @example Otro o no especificado
			 */
			urban_area_name: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	AppController_getHello: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	CountryController_getAll: {
		parameters: {
			query?: {
				/** @description Filtro por nombre (búsqueda parcial ilike) */
				name?: string;
				/** @description Filtro por código ISO alpha-2 */
				isoAlpha2Code?: string;
				/** @description Filtro por código ISO alpha-3 */
				isoAlpha3Code?: string;
				/** @description Filtro por código numérico ISO */
				isoNumericCode?: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description List of countries */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CountryDto"][];
				};
			};
		};
	};
	CountryController_getById: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Country details */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CountryDto"];
				};
			};
			/** @description Country not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	DepartmentController_findAll: {
		parameters: {
			query?: {
				/** @description Filtro por nombre (búsqueda parcial) */
				name?: string;
				/** @description Filtro por código DANE */
				daneCode?: string;
				/** @description Filtro por ID del país */
				countryId?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description List of departments */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DepartmentDto"][];
				};
			};
		};
	};
	DepartmentController_findOne: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Department details */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DepartmentDto"];
				};
			};
			/** @description Department not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	CityController_getAll: {
		parameters: {
			query?: {
				/** @description Filtro por ID del país */
				countryId?: number;
				/** @description Filtro por ID del departamento */
				departmentId?: number;
				/** @description Filtro por nombre de ciudad (búsqueda parcial) */
				name?: string;
				/** @description Filtro por código DANE */
				daneCode?: string;
				/** @description Filtro por nombre de país (búsqueda parcial) */
				countryName?: string;
				/** @description Filtro por nombre de departamento (búsqueda parcial) */
				departmentName?: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description List of cities with relations */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CityWithRelationsDto"][];
				};
			};
		};
	};
	CityController_getById: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description City details */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CityDto"];
				};
			};
			/** @description City not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	NeighborhoodController_getByPoint: {
		parameters: {
			query: {
				/** @description Longitud geográfica (WGS84, entre -180 y 180) */
				longitude: number;
				/** @description Latitud geográfica (WGS84, entre -90 y 90) */
				latitude: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Neighborhood at the given coordinates */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["NeighborhoodDto"];
				};
			};
			/** @description No neighborhood found at the given coordinates */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
}
