/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/api/v1/cities": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Obtener todas las ciudades
		 * @description Recupera una lista de ciudades con la posibilidad de aplicar filtros
		 */
		get: {
			parameters: {
				query?: {
					/**
					 * @description Filtra las ciudades por ID de país. Si se usa, se ignora countryName
					 * @example 48
					 */
					countryId?: number;
					/**
					 * @description Filtra las ciudades por ID de departamento. Si se usa, se ignora departmentName
					 * @example 5
					 */
					departmentId?: number;
					/**
					 * @description Filtra las ciudades por nombre (búsqueda parcial, case-insensitive)
					 * @example SANTO
					 */
					name?: string;
					/**
					 * @description Filtra las ciudades por código DANE exacto
					 * @example 685
					 */
					daneCode?: string;
					/**
					 * @description Filtra las ciudades por nombre del país (búsqueda parcial). Solo se aplica si no se envía countryId
					 * @example Colombia
					 */
					countryName?: string;
					/**
					 * @description Filtra las ciudades por nombre del departamento (búsqueda parcial). Solo se aplica si no se envía departmentId
					 * @example Atlántico
					 */
					departmentName?: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Lista de ciudades encontradas */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						/** @example [
						 *       {
						 *         "id": 898,
						 *         "name": "SANTO TOMAS",
						 *         "dane_code": "685",
						 *         "department_id": 5,
						 *         "country_id": 48,
						 *         "active": true,
						 *         "created_at": "2025-10-24T13:50:50.892312+00:00",
						 *         "updated_at": "2025-10-24T13:50:50.892312+00:00",
						 *         "country_name_es": "Colombia",
						 *         "department_name": "Atlántico"
						 *       }
						 *     ] */
						"application/json": components["schemas"]["CityWithRelations"][];
					};
				};
				/** @description Error del servidor */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/cities/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Obtener una ciudad por ID
		 * @description Recupera la información de una ciudad específica por su ID
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/**
					 * @description ID de la ciudad
					 * @example 898
					 */
					id: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Información de la ciudad */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						/** @example {
						 *       "id": 898,
						 *       "name": "SANTO TOMAS",
						 *       "dane_code": "685",
						 *       "department_id": 5,
						 *       "country_id": 48,
						 *       "active": true,
						 *       "created_at": "2025-10-24T13:50:50.892312+00:00",
						 *       "updated_at": "2025-10-24T13:50:50.892312+00:00"
						 *     } */
						"application/json": components["schemas"]["City"];
					};
				};
				/** @description Ciudad no encontrada */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						/** @example {
						 *       "message": "City not found"
						 *     } */
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description Error del servidor */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/countries": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Obtener todos los países
		 * @description Recupera una lista de países con la posibilidad de aplicar filtros
		 */
		get: {
			parameters: {
				query?: {
					/**
					 * @description Filtra los países por nombre (búsqueda parcial)
					 * @example Colombia
					 */
					name?: string;
					/**
					 * @description Filtra los países por código ISO Alpha-2
					 * @example CO
					 */
					isoAlpha2Code?: string;
					/**
					 * @description Filtra los países por código ISO Alpha-3
					 * @example COL
					 */
					isoAlpha3Code?: string;
					/**
					 * @description Filtra los países por código ISO numérico
					 * @example 170
					 */
					isoNumericCode?: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Lista de países encontrados */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						/** @example [
						 *       {
						 *         "id": 48,
						 *         "name_es": "Colombia",
						 *         "name_en": "Colombia",
						 *         "iso_alpha2_code": "CO",
						 *         "iso_alpha3_code": "COL",
						 *         "iso_numeric_code": "170",
						 *         "active": true,
						 *         "created_at": "2025-10-24T13:50:50.892312+00:00",
						 *         "updated_at": "2025-10-24T13:50:50.892312+00:00"
						 *       }
						 *     ] */
						"application/json": components["schemas"]["Country"][];
					};
				};
				/** @description Error del servidor */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/countries/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Obtener un país por ID
		 * @description Recupera la información de un país específico por su ID
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/**
					 * @description ID del país
					 * @example 48
					 */
					id: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Información del país */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						/** @example {
						 *       "id": 48,
						 *       "name_es": "Colombia",
						 *       "name_en": "Colombia",
						 *       "iso_alpha2_code": "CO",
						 *       "iso_alpha3_code": "COL",
						 *       "iso_numeric_code": "170",
						 *       "active": true,
						 *       "created_at": "2025-10-24T13:50:50.892312+00:00",
						 *       "updated_at": "2025-10-24T13:50:50.892312+00:00"
						 *     } */
						"application/json": components["schemas"]["Country"];
					};
				};
				/** @description País no encontrado */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						/** @example {
						 *       "message": "Country not found"
						 *     } */
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description Error del servidor */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/departments": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Obtener todos los departamentos
		 * @description Recupera una lista de departamentos con la posibilidad de aplicar filtros
		 */
		get: {
			parameters: {
				query?: {
					/**
					 * @description Filtra los departamentos por nombre (búsqueda parcial)
					 * @example Atlántico
					 */
					name?: string;
					/**
					 * @description Filtra los departamentos por código DANE exacto
					 * @example 08
					 */
					daneCode?: string;
					/**
					 * @description Filtra los departamentos por ID de país
					 * @example 48
					 */
					countryId?: number;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Lista de departamentos encontrados */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						/** @example [
						 *       {
						 *         "id": 5,
						 *         "name": "Atlántico",
						 *         "dane_code": "08",
						 *         "country_id": 48,
						 *         "active": true,
						 *         "created_at": "2025-10-24T13:50:50.892312+00:00",
						 *         "updated_at": "2025-10-24T13:50:50.892312+00:00"
						 *       }
						 *     ] */
						"application/json": components["schemas"]["Department"][];
					};
				};
				/** @description Error del servidor */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/departments/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Obtener un departamento por ID
		 * @description Recupera la información de un departamento específico por su ID
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/**
					 * @description ID del departamento
					 * @example 5
					 */
					id: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Información del departamento */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						/** @example {
						 *       "id": 5,
						 *       "name": "Atlántico",
						 *       "dane_code": "08",
						 *       "country_id": 48,
						 *       "active": true,
						 *       "created_at": "2025-10-24T13:50:50.892312+00:00",
						 *       "updated_at": "2025-10-24T13:50:50.892312+00:00"
						 *     } */
						"application/json": components["schemas"]["Department"];
					};
				};
				/** @description Departamento no encontrado */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						/** @example {
						 *       "message": "Department not found"
						 *     } */
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description Error del servidor */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/neighborhoods/point": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Obtener barrio por coordenadas geográficas
		 * @description Busca el barrio que contiene un punto geográfico específico basado en coordenadas de longitud y latitud
		 */
		get: {
			parameters: {
				query: {
					/**
					 * @description Longitud del punto geográfico (coordenada X)
					 * @example -74.0833
					 */
					longitude: number;
					/**
					 * @description Latitud del punto geográfico (coordenada Y)
					 * @example 4.6097
					 */
					latitude: number;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Información del barrio encontrado en las coordenadas especificadas */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						/** @example {
						 *       "neighborhood_id": 123,
						 *       "neighborhood_name": "Centro",
						 *       "city_id": 898,
						 *       "city_name": "Bogotá",
						 *       "department_id": 5,
						 *       "department_name": "Cundinamarca",
						 *       "country_id": 48,
						 *       "country_name": "Colombia",
						 *       "context": {
						 *         "longitude": -74.0833,
						 *         "latitude": 4.6097
						 *       }
						 *     } */
						"application/json": {
							/** @description ID del barrio */
							neighborhood_id?: number;
							/** @description Nombre del barrio */
							neighborhood_name?: string;
							/** @description ID de la ciudad */
							city_id?: number;
							/** @description Nombre de la ciudad */
							city_name?: string;
							/** @description ID del departamento */
							department_id?: number;
							/** @description Nombre del departamento */
							department_name?: string;
							/** @description ID del país */
							country_id?: number;
							/** @description Nombre del país */
							country_name?: string;
							context?: {
								longitude?: number;
								latitude?: number;
							};
						};
					};
				};
				/** @description Parámetros inválidos o faltantes */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						/** @example {
						 *       "message": "Invalid request params, missing longitude or latitude"
						 *     } */
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description No se encontró ubicación para las coordenadas especificadas */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": {
							/** @example No se encontro la locacion solicitada */
							message?: string;
							context?: {
								longitude?: number;
								latitude?: number;
							};
						};
					};
				};
				/** @description Error del servidor */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Endpoint de salud del servicio
		 * @description Verifica que el servicio esté funcionando correctamente
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Servicio funcionando correctamente */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		City: {
			/**
			 * @description ID único de la ciudad
			 * @example 898
			 */
			id?: number;
			/**
			 * @description Nombre de la ciudad
			 * @example SANTO TOMAS
			 */
			name?: string;
			/**
			 * @description Código DANE de la ciudad
			 * @example 685
			 */
			dane_code?: string | null;
			/**
			 * @description ID del departamento al que pertenece
			 * @example 5
			 */
			department_id?: number;
			/**
			 * @description ID del país al que pertenece
			 * @example 48
			 */
			country_id?: number;
			/**
			 * @description Indica si la ciudad está activa
			 * @example true
			 */
			active?: boolean;
			/**
			 * Format: date-time
			 * @description Fecha de creación
			 */
			created_at?: string;
			/**
			 * Format: date-time
			 * @description Fecha de última actualización
			 */
			updated_at?: string;
		};
		CityWithRelations: {
			/** @example 898 */
			id?: number;
			/** @example SANTO TOMAS */
			name?: string;
			/** @example 685 */
			dane_code?: string | null;
			/** @example 5 */
			department_id?: number;
			/** @example 48 */
			country_id?: number;
			/** @example true */
			active?: boolean;
			/** Format: date-time */
			created_at?: string;
			/** Format: date-time */
			updated_at?: string;
			/**
			 * @description Nombre del país en español
			 * @example Colombia
			 */
			country_name_es?: string;
			/**
			 * @description Nombre del departamento
			 * @example Atlántico
			 */
			department_name?: string;
		};
		Country: {
			/**
			 * @description ID único del país
			 * @example 48
			 */
			id?: number;
			/**
			 * @description Nombre del país en español
			 * @example Colombia
			 */
			name_es?: string;
			/**
			 * @description Nombre del país en inglés
			 * @example Colombia
			 */
			name_en?: string | null;
			/**
			 * @description Código ISO Alpha-2
			 * @example CO
			 */
			iso_alpha2_code?: string | null;
			/**
			 * @description Código ISO Alpha-3
			 * @example COL
			 */
			iso_alpha3_code?: string | null;
			/**
			 * @description Código ISO numérico
			 * @example 170
			 */
			iso_numeric_code?: string | null;
			/**
			 * @description Indica si el país está activo
			 * @example true
			 */
			active?: boolean;
			/** Format: date-time */
			created_at?: string;
			/** Format: date-time */
			updated_at?: string;
		};
		Department: {
			/**
			 * @description ID único del departamento
			 * @example 5
			 */
			id?: number;
			/**
			 * @description Nombre del departamento
			 * @example Atlántico
			 */
			name?: string;
			/**
			 * @description Código DANE del departamento
			 * @example 08
			 */
			dane_code?: string | null;
			/**
			 * @description ID del país al que pertenece
			 * @example 48
			 */
			country_id?: number;
			/**
			 * @description Indica si el departamento está activo
			 * @example true
			 */
			active?: boolean;
			/** Format: date-time */
			created_at?: string;
			/** Format: date-time */
			updated_at?: string;
		};
		NeighborhoodByPoint: {
			/** @description ID del barrio */
			neighborhood_id?: number;
			/** @description Nombre del barrio */
			neighborhood_name?: string;
			/** @description ID de la ciudad */
			city_id?: number;
			/** @description Nombre de la ciudad */
			city_name?: string;
			/** @description ID del departamento */
			department_id?: number;
			/** @description Nombre del departamento */
			department_name?: string;
			/** @description ID del país */
			country_id?: number;
			/** @description Nombre del país */
			country_name?: string;
		};
		ErrorResponse: {
			/**
			 * @description Mensaje de error
			 * @example City not found
			 */
			message?: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
